### ***We will learn different methods to Apply Hyperparameter tuning on the model and find the best parameters for the model***

In [2]:
# import necessary modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split, KFold , StratifiedKFold ,cross_val_score
from sklearn.metrics import r2_score

In [3]:
# load the dataset we want
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv')

print(df.head())

      crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [ ]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64
 4   nox      506 non-null    float64
 5   rm       506 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64
 9   tax      506 non-null    int64
 10  ptratio  506 non-null    float64
 11  b        506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB
None

### Fitting the Default Model With 5 fold cross validation

In [12]:
# Prepare the data

X = df.iloc[:,:-1]
y = df.iloc[:,-1]

# Let us fit the KNeighborsRegressor Model default values
knn = KNeighborsRegressor(n_neighbors=3 , weights='uniform' , p=2)

kf =  KFold(n_splits = 5 , shuffle=True,random_state=1)

scores = cross_val_score(knn , X,y, cv = kf , scoring='r2')

print(f"Scores -> {scores}")
print(f"Best Score -> {scores.mean()}")

Scores -> [0.59758726 0.26209867 0.54604255 0.37452435 0.58663289]
Best Score -> 0.4733771426224149

### Let us Now use  Hyperparameter tuning

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.2, random_state=42)

param_grid = {
    'n_neighbors' : [1,3,4,5,6],
    'weights':['uniform','distance'],
    'algorithm':['brute','ball_tree','kd_tree'],
    'p': [1,2]
}

from sklearn.model_selection import GridSearchCV

grid = GridSearchCV(knn , param_grid , cv = kf , scoring='r2')

grid.fit(X_train,y_train)

print(grid.best_params_)

{'algorithm': 'brute', 'n_neighbors': 4, 'p': 1, 'weights': 'distance'}

In [26]:
pd.DataFrame(grid.cv_results_).sort_values(by='mean_test_score' , ascending=False)

    mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
9        0.004087      0.000318  ...        0.089458                1
29       0.003713      0.000967  ...        0.089458                1
49       0.003208      0.000287  ...        0.089458                1
17       0.004020      0.000658  ...        0.064410                4
37       0.003783      0.000712  ...        0.064410                4
57       0.002929      0.000303  ...        0.064410                4
25       0.003130      0.000235  ...        0.100557                7
45       0.003635      0.000489  ...        0.100557                7
5        0.002660      0.000096  ...        0.100557                7
13       0.003363      0.000416  ...        0.072786               10
53       0.002919      0.000166  ...        0.072786               10
33       0.003205      0.000516  ...        0.072786               10
44       0.003992      0.000557  ...        0.120327               13
24       0.003338      0.000302  ...        0.120327               13
4        0.002812      0.000217  ...        0.120327               13
8        0.003797      0.000551  ...        0.128155               16
28       0.002909      0.000414  ...        0.128155               16
48       0.003397      0.000505  ...        0.128155               16
56       0.003029      0.000463  ...        0.068504               19
36       0.003685      0.000821  ...        0.068504               19
16       0.003389      0.000688  ...        0.068504               19
12       0.003010      0.000216  ...        0.087841               22
32       0.003042      0.000579  ...        0.087841               22
52       0.003305      0.000244  ...        0.087841               22
59       0.003069      0.000422  ...        0.086414               25
39       0.003408      0.000316  ...        0.086414               25
19       0.004117      0.000804  ...        0.086414               27
35       0.003231      0.000265  ...        0.088099               28
55       0.003116      0.000411  ...        0.088099               28
15       0.003823      0.000576  ...        0.088099               30
51       0.003175      0.000469  ...        0.108449               31
31       0.003102      0.000601  ...        0.108449               31
11       0.003897      0.000515  ...        0.108449               33
41       0.003652      0.000284  ...        0.230025               34
21       0.003669      0.000345  ...        0.230025               34
1        0.004023      0.000347  ...        0.230025               34
20       0.004251      0.000356  ...        0.230025               37
40       0.003408      0.000405  ...        0.230025               37
0        0.005018      0.000966  ...        0.230025               37
18       0.003461      0.000449  ...        0.098368               40
38       0.003322      0.000446  ...        0.098368               40
58       0.003583      0.000703  ...        0.098368               40
50       0.003120      0.000359  ...        0.112501               43
10       0.003402      0.000591  ...        0.112501               43
30       0.003074      0.000531  ...        0.112501               43
27       0.002766      0.000153  ...        0.121493               46
47       0.003059      0.000284  ...        0.121493               46
7        0.003663      0.000070  ...        0.121493               48
54       0.003138      0.000370  ...        0.104923               49
34       0.004334      0.000771  ...        0.104923               49
14       0.003706      0.000866  ...        0.104923               49
6        0.003248      0.000344  ...        0.112047               52
26       0.002824      0.000149  ...        0.112047               52
46       0.003086      0.000361  ...        0.112047               52
3        0.003027      0.000415  ...        0.214378               55
2        0.004310      0.001550  ...        0.214378               55
22       0.003342      0.000596  ...        0.214378               55
23       0.003311      0.000373  ...        0.214378               55
43       0.003269      0.000239  ...        0.214378               55
42       0.004421      0.000965  ...        0.214378               55

[60 rows x 17 columns]

In [27]:
grid.best_estimator_

KNeighborsRegressor(algorithm='brute', n_neighbors=4, p=1, weights='distance')

In [28]:
grid.best_score_ # This is the mean score of the model with best parameters

np.float64(0.598462075871436)

In [29]:
y_pred = grid.predict(X_test)

print(f"r2_score -> {r2_score(y_test , y_pred)}")

r2_score -> 0.7179406084711986

### GridSearchCV is a brute force algo, which fits all the pssible paramters combinations - Can take a very long time if there are high no. of models to train

### So we use RandomisedsearchCV sometimes

In [31]:
from sklearn.model_selection import RandomizedSearchCV

grid = RandomizedSearchCV(knn ,param_grid , cv = kf , scoring='r2')

grid.fit(X_train , y_train)

print(grid.best_params_)

{'weights': 'distance', 'p': 1, 'n_neighbors': 6, 'algorithm': 'brute'}

In [34]:
pd.DataFrame(grid.cv_results_).sort_values(by='mean_test_score' , ascending=False)

   mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.004605      0.000657  ...        0.064410                1
9       0.002969      0.000612  ...        0.120327                2
1       0.003980      0.001511  ...        0.068504                3
3       0.003491      0.000552  ...        0.088099                4
6       0.002857      0.000177  ...        0.108449                5
4       0.003697      0.000290  ...        0.098368                6
2       0.004465      0.000194  ...        0.121493                7
5       0.002810      0.000139  ...        0.104923                8
8       0.003039      0.000397  ...        0.104923                8
7       0.002975      0.000355  ...        0.214378               10

[10 rows x 17 columns]

- Here we see only 10 models were fit since by default n_iter = 10 , but we can specify our own also

In [35]:
# Choosing our own number of iterations

from sklearn.model_selection import RandomizedSearchCV

grid = RandomizedSearchCV(knn ,param_grid ,n_iter = 30, cv = kf , scoring='r2')

grid.fit(X_train , y_train)

print(grid.best_params_)

{'weights': 'distance', 'p': 1, 'n_neighbors': 4, 'algorithm': 'brute'}